config/routes.rb
Dashboard::Application.routes.draw do
  root :to => 'welcome#index'
 
  get "profiles/dashboard"
 
  match '/profiles/dashboard' => 'profiles#dashboard', :as => :user_root

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"

  resources :profiles, :only => [:dashboard]
  
  namespace :admin do
    match '/'     => 'users#index'
    match 'index' => 'users#index'
    resources :users
    resources :customers
    resources :puppetmasters do
      member do
        get 'check_connection_status'
        get 'pair_with_puppetmaster'
      end
    end
    get "utils/generate_csr"
    post "utils/generate_csr"
    post "utils/save_to_file"

  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :puppetmasters

  attr_accessible :githubrepo_url, :name, :puppetdb_url, :user_ids

  validates :name, presence: true

  validates :githubrepo_url, github_url: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  attr_accessible :name
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::AdminController
  load_and_authorize_resource

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to admin_customer_path(@customer), notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to admin_customer_path(@customer), notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    for pm in Puppetmaster.find(:all)
      pm.destroy if @customer.puppetmasters.include?(pm)
    end
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to admin_customers_path }
      format.json { head :no_content }
    end
  end
end

app/views/admin/customers/_form.html.erb
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'input-xlarge' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :puppetdb_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.url_field :puppetdb_url, :class => 'input-xlarge' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :githubrepo_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.url_field :githubrepo_url, :class => 'input-xlarge' %>
    </div>
  </div>
<% if @customer.persisted? %>
  <div class ="control-group">
    <label class="control-label">Users</label>
    <div class="controls">
      <%= f.collection_select :user_ids, User.all, :id, :email, {:selected => @customer.user_ids}, {:multiple => true} %>
    </div> 
  </div>
<% end %>
  <div class="control-group">
    <div class="controls">
      <%= f.submit :class => 'btn btn-success' %>
      <%= button_tag "Reset", type: :reset, :class => 'btn btn-danger' %>
      <%= link_to "Cancel", admin_customers_path, :class => 'btn btn-default' %>
    </div>
  </div>

app/views/admin/customers/edit.html.erb
<h1>Editing customer</h1>

<%= form_for [:admin, @customer], :url => admin_customer_path(@customer), :method => :put, :html => { :class => "form-horizontal", :id => "edit_customer" } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/admin/customers/index.html.erb
<h1>Listing customers</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Puppetmasters</th>
      <th>Puppetdb url</th>
      <th>Githubrepo url</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
<% @customers.each do |customer| %>
    <tr>
      <td><%= link_to customer.name, admin_customer_path(customer) %></td>
      <td>
        <% for pm in Puppetmaster.find(:all) %>
          <%= pm.url if customer.puppetmasters.include?(pm) %>
        <% end %>
      </td>
      <td><%= customer.puppetdb_url %></td>
      <td><%= customer.githubrepo_url %></td>
      <td>
        <%= link_to 'Show', admin_customer_path(customer), :class => "btn btn-link" %>
      <% if can? :update, customer %>
        <%= link_to 'Edit', edit_admin_customer_path(customer), :class => "btn btn-link" %>
        <%= link_to 'Destroy', admin_customer_path(customer), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-link" %>
      <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<br />

<% if can? :update, @customers %>
  <%= link_to 'New Customer', new_admin_customer_path, :class => 'btn btn-primary', :role => 'button' %>
<% end %>

app/views/admin/customers/new.html.erb
<h1>New customer</h1>

<%= form_for [:admin, @customer], :url => admin_customers_path, :html => { :class => "form-horizontal" } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/admin/customers/show.html.erb
<h1>Customer Detail</h1>

<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <tr>
  	<td>Name:</td>
  	<td><%= @customer.name %></td>
  </tr>
  <tr>
	<td>Puppetmasters:</td>
    <td>
      <% for pm in Puppetmaster.find(:all) %>
        <% if @customer.puppetmasters.include?(pm) %>
          <%= link_to pm.url, admin_puppetmaster_path(pm) %>
        <% end %>
      <% end; %>
      <%= link_to "New", new_admin_puppetmaster_path(:customer => @customer.id), :class => 'btn btn-primary', :role => 'button' %>
    </td>
  </tr>
  <tr>
    <td>Puppetdb url:</td>
    <td><%= @customer.puppetdb_url %></td>
  </tr>
  <tr>
    <td>Githubrepo url:</td>
  	<td><%= @customer.githubrepo_url %></td>
  </tr>
  <tr>
    <td>Users:</td>
    <td>
      <% for user in User.find(:all) %>
        <%= user.email if @customer.users.include?(user) %>
      <% end %>
    </td>
  </tr>
 </table>

<div class ="control-group">
  <div class="controls">
    <%= link_to "Back", admin_customers_path, :class => 'btn btn-default', :role => 'button' %>
<% if can? :update, @customer %>
    <%= link_to "Edit", edit_admin_customer_path(@customer), :class => 'btn btn-default', :role => 'button' %>
    <%= link_to "Delete", admin_customer_path(@customer), :method => "delete", :confirm => "Are you sure?", :class => 'btn btn-danger', :role => 'button' %>
<% end %>
  </div>
</div>