config/routes.rb
Dashboard::Application.routes.draw do
  root :to => 'welcome#index'
 
  get "profiles/dashboard"
 
  match '/profiles/dashboard' => 'profiles#dashboard', :as => :user_root

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"

  resources :profiles, :only => [:dashboard]
  
  namespace :admin do
    match '/'     => 'users#index'
    match 'index' => 'users#index'
    resources :users
    resources :customers
    resources :puppetmasters do
      member do
        get 'check_connection_status'
        get 'pair_with_puppetmaster'
      end
    end
    get "utils/generate_csr"
    post "utils/generate_csr"
    post "utils/save_to_file"

  end

end

app/controllers/admin/utils_controller.rb
class Admin::UtilsController < Admin::AdminController
  # before_filter { |c| c.verify_admin true}
  include Admin::UtilsHelper

  def generate_csr
    if !params['cert'].blank?
      @certname = params['cert']['certname'].blank? ? 'dashboard' : params['cert']['certname']
      @certdomain = params['cert']['certdomain'].blank? ? 'nvisionary.com' : params['cert']['certdomain']
    else
      @certname = 'dashboard'
      @certdomain = 'nvisionary.com'
    end
    if !params['certificate'].blank?
      @certpath = params['certificate']['certpath'].blank? ? "config/ssl/#{@certname}.#{@certdomain}.csr" : params['certificate']['certpath']
      @certkeypath = params['certificate']['certkeypath'].blank? ? "config/ssl/#{@certname}.#{@certdomain}.key" : params['certificate']['certkeypath']
    else
      @certpath = "config/ssl/#{@certname}.#{@certdomain}.csr"
      @certkeypath = "config/ssl/#{@certname}.#{@certdomain}.key"
    end

    @cert, @key = create_cert_key(@certname, @certdomain)
 
    respond_to do |format|
      format.html # generate_cert.html.erb
      format.js { render :layout => false }
    end
  end

  def save_to_file
    @certpath = params['certificate']['certpath']
    @certdata = params['certificate']['cert']

    save_data_to_file(@certpath, @certdata)

    respond_to do |format|
      format.js { render :layout => false }
    end
  end
end

app/helpers/admin/utils_helper.rb
require 'openssl'
require "net/https"
require "uri"

module Admin::UtilsHelper
  def create_cert_key (certname, certdomain)
  	# return WEBrick::Utils::create_self_signed_cert(1024, [['CN', certname + "." + certdomain], ['DC', certdomain]], certcomment)
    key = OpenSSL::PKey::RSA.new(1024)
    request = OpenSSL::X509::Request.new
    request.version = 0 
    request.subject = OpenSSL::X509::Name.new([
      ['CN', certname + "." + certdomain, OpenSSL::ASN1::UTF8STRING]
    ])  
    request.public_key = key.public_key
    request.sign(key, OpenSSL::Digest::SHA1.new)
    return [ request, key ]
  end

  def save_data_to_file (filename, data)
    begin
      file = File.open(filename, "w")
      file.write (data)
    rescue IOError => e
      logger.debug "Error: #{e}"
    ensure
      file.close unless file == nil
    end
  end

  def file_exists (filename)
    return File.file?(filename)
  end

  def can_connect_to (server, port, request, certfile=nil, keyfile=nil)
    uri = URI.parse(server + ":" + port + "/" + request)
    if !certfile.nil?
      cert = File.read(certfile)
      key = File.read(keyfile)
    end
    http = Net::HTTP.new(uri.host, uri.port)
    if !certfile.nil?
      http.use_ssl = true
      http.cert = OpenSSL::X509::Certificate.new(cert)
      http.key = OpenSSL::PKey::RSA.new(key)
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    end

    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)
    if response.is_a?(Net::HTTPSuccess)
      return true
    else
      return false
    end
  end

  def submit_csr (server, port, request, csr)
    uri = URI.parse(server + ":" + port + request + File.basename(csr, ".csr"))
    logger.debug("URI: #{uri}")

    file = File.open(csr)
    put_body = file.read
    file.close

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Put.new(uri.request_uri)
    request.body = put_body.to_s
    request["Content-Type"] = "text/plain"
    response = http.request(request)
    if response.is_a?(Net::HTTPSuccess)
      return true
    else
      if response.body =~ /already has a requested certificate/
        return true
      elsif response.body =~ /already has a signed certificate/
        return true
      else
        logger.debug("POST error: #{response.code} - #{response.message} - #{response.body}")
        return false
      end
    end
  end

  def get_signed_cert (server, port, request, csr)
    uri = URI.parse(server + ":" + port + request + File.basename(csr, ".csr") )
    logger.debug("URI: #{uri}")

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new(uri.request_uri, {"Accept" => "s"})
    response = http.request(request)
    if response.is_a?(Net::HTTPSuccess)
      filename = File.dirname(csr) + "/" + File.basename(csr, ".csr") + ".pem"
      save_data_to_file(filename, response.body.to_s)
      return filename
    else
      logger.debug("GET error: #{response.code} - #{response.message} - #{response.body}")
      return false
    end
  end
end

app/views/admin/utils/generate_cert.html.erb
<h1>Generate SSL certificates for use with Puppet masters</h1>

<div id="flash_notice" style="display:none"></div>

<%= form_for :cert, :url => admin_utils_generate_cert_path, :remote => true, :html => { :class => "form-horizontal", :id => "generate_certificate" } do |f| -%>
  <legend>Cert input data</legend>
  <div class="control-group">
    <%= f.label :certname, "Name on Certificate", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :certname, :class => 'input-xlarge', :value => @certname %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :certdomain, "Domain on Certificate", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :certdomain, :class => 'input-xlarge', :value => @certdomain %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :certcomment, "Comment on Certificate", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :certcomment, :class => 'input-xlarge', :value => @certcomment %>
    </div>
  </div>
  <div class ="control-group">
    <div class="controls">
      <%= f.submit :class => 'btn btn-success', :value => "Create Cert" %>
      <%= button_tag "Reset", type: :reset, :class => 'btn btn-danger' %>
      <%= link_to "Cancel", admin_users_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end -%>
<%= form_for :certificate, :url => admin_utils_save_to_file_path, :remote => true, :html => { :class => "form-horizontal", :id => "generated_certificate" } do |f| -%>
  <legend>Generated cert data</legend>
  <div class="control-group">
    <%= f.label :cert, "Certificate", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :cert, :class => 'form-control', :size => '', :value => @cert, :readonly => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :certpath, "Certificate path", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :certpath, :class => 'input-xlarge', :value => @certpath %>
    </div>
  </div>
  <div class ="control-group">
    <div class="controls">
      <%= f.submit :class => 'btn btn-success', :value => "Save to file" %>
      <%= button_tag "Reset", type: :reset, :class => 'btn btn-danger' %>
    </div>
  </div>
<% end -%>
<%= form_for :certificate, :url => admin_utils_save_to_file_path, :remote => true, :html => { :class => "form-horizontal", :id => "generated_certificate_key" } do |f| -%>
  <legend>Generated cert key</legend>
  <div class="control-group">
    <%= f.label :key, "Key", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :cert, :class => 'form-control', :size => '', :value => @key, :readonly => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :certkeypath, "Certificate Key path", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :certpath, :class => 'input-xlarge', :value => @certkeypath %>
    </div>
  </div>
  <div class ="control-group">
    <div class="controls">
      <%= f.submit :class => 'btn btn-success', :value => "Save to file" %>
      <%= button_tag "Reset", type: :reset, :class => 'btn btn-danger' %>
    </div>
  </div>
<% end -%>

app/views/admin/utils/generate_cert.js.erb
/*Hide the flash notice div*/
$("#flash_notice").hide(300);

/*Update the html of the div post_errors with the new one*/
$("#flash_notice").html("<div class=\"alert fade in alert-success\">New certificate and key generated</div>");

/*Show the div post_errors*/
$("#flash_notice").show(300);

$("#certificate_cert").val("<%= @cert.to_s.gsub!(/\n/, '\n') %>");
$("#certificate_key_key").val("<%= @key.to_s.gsub!(/\n/, '\n') %>");

app/views/admin/utils/generate_csr.html.erb
<h1>Generate SSL certificates for use with Puppet masters</h1>

<div id="flash_notice" style="display:none"></div>

<%= form_for :cert, :url => admin_utils_generate_csr_path, :remote => true, :html => { :class => "form-horizontal", :id => "generate_certificate" } do |f| -%>
  <legend>Cert input data</legend>
  <div class="control-group">
    <%= f.label :certname, "Name on Certificate", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :certname, :class => 'input-xlarge', :value => @certname %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :certdomain, "Domain on Certificate", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :certdomain, :class => 'input-xlarge', :value => @certdomain %>
    </div>
  </div>
  <div class ="control-group">
    <div class="controls">
      <%= f.submit :class => 'btn btn-success', :value => "Create Cert" %>
      <%= button_tag "Reset", type: :reset, :class => 'btn btn-danger' %>
      <%= link_to "Cancel", admin_users_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end -%>
<%= form_for :certificate, :url => admin_utils_save_to_file_path, :remote => true, :html => { :class => "form-horizontal", :id => "generated_certificate_req" } do |f| -%>
  <legend>Generated cert request data</legend>
  <div class="control-group">
    <%= f.label :cert, "Certificate Request", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :cert, :class => 'form-control', :size => '', :value => @cert, :readonly => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :certpath, "Certificate path", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :certpath, :class => 'input-xlarge', :value => @certpath %>
    </div>
  </div>
  <div class ="control-group">
    <div class="controls">
      <%= f.submit :class => 'btn btn-success', :value => "Save to file" %>
      <%= button_tag "Reset", type: :reset, :class => 'btn btn-danger' %>
    </div>
  </div>
<% end -%>
<%= form_for :certificate, :url => admin_utils_save_to_file_path, :remote => true, :html => { :class => "form-horizontal", :id => "generated_certificate_key" } do |f| -%>
  <legend>Generated cert key</legend>
  <div class="control-group">
    <%= f.label :key, "Key", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :cert, :class => 'form-control', :size => '', :value => @key, :readonly => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :certkeypath, "Certificate Key path", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :certpath, :class => 'input-xlarge', :value => @certkeypath %>
    </div>
  </div>
  <div class ="control-group">
    <div class="controls">
      <%= f.submit :class => 'btn btn-success', :value => "Save to file" %>
      <%= button_tag "Reset", type: :reset, :class => 'btn btn-danger' %>
    </div>
  </div>
<% end -%>

app/views/admin/utils/generate_csr.js.erb
/*Hide the flash notice div*/
$("#flash_notice").hide(300);

/*Update the html of the div post_errors with the new one*/
$("#flash_notice").html("<div class=\"alert fade in alert-success\">New certificate and key generated</div>");

/*Show the div post_errors*/
$("#flash_notice").show(300);

$("#certificate_cert").val("<%= @cert.to_s.gsub!(/\n/, '\n') %>");
$("#certificate_key_key").val("<%= @key.to_s.gsub!(/\n/, '\n') %>");

app/views/admin/utils/save_to_file.js.erb
  /*Hide the flash notice div*/
  $("#flash_notice").hide(300);

  /*Update the html of the div post_errors with the new one*/
  $("#flash_notice").html("<div class=\"alert fade in alert-success\">Saved data to <%= @certpath %></div>");

  /*Show the div post_errors*/
  $("#flash_notice").show(300);