config/routes.rb
Dashboard::Application.routes.draw do
  root :to => 'welcome#index'
 
  get "profiles/dashboard"
 
  match '/profiles/dashboard' => 'profiles#dashboard', :as => :user_root

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"

  resources :profiles, :only => [:dashboard]
  
  namespace :admin do
    match '/'     => 'users#index'
    match 'index' => 'users#index'
    resources :users
    resources :customers
    resources :puppetmasters do
      member do
        get 'check_connection_status'
        get 'pair_with_puppetmaster'
      end
    end
    get "utils/generate_csr"
    post "utils/generate_csr"
    post "utils/save_to_file"

  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dashboard-Admin" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= nav_bar :fixed => :top, :brand => "Dashboard-Admin", :inverse => true, :responsive => true do %>
      <%= menu_group :pull => :left do %>
        <%= drop_down "Users" do %>
          <%= menu_item "Index", admin_index_path %>
          <% if can? :update, @users %>
            <%= menu_item "Create", new_admin_user_path %>
          <% end %>
        <% end %>
        <%= drop_down "Customers" do %>
          <%= menu_item "Index", admin_customers_path %>
          <% if can? :update, @customers %>
            <%= menu_item "Create", new_admin_customer_path %>
          <% end %>
        <% end %>
        <%= drop_down "Utilities" do %>
          <%= menu_item "Generate csr", admin_utils_generate_csr_path %>
        <% end %>
      <% end %>
      <%= menu_group :pull => :right do %>
        <% if current_user %>
          <%= menu_item "Log Out", destroy_user_session_path, :method => 'delete' %>
        <% else %>
          <%= menu_item "Log in", new_user_session_path %>
        <% end %>
      <% end %>
   <% end %>   

  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span9">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div><!--/row-->
  </div>

  <div class="container-fluid" id="footer">
    <div class="row-fluid">
      <footer>
        <p>&copy; nVisionary, Inc. 2014</p>
      </footer>
    </div>
  </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dashboard" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= nav_bar :fixed => :top, :brand => "Dashboard", :inverse => true, :responsive => true do %>
      <%= menu_group :pull => :left do %>
        <%= menu_item "Home", root_path %>
        <%= menu_item "Path 1", "#" %>
        <%= menu_item "Path 2", "#" %>
      <% end %>
      <%= menu_group :pull => :right do %>
        <% if current_user %>
          <%= drop_down current_user.email do %>
            <% if (current_user.role? :admin) || (current_user.role? :developer) %>
              <%= menu_item "Admin console", user_root_path %>
            <% end %>
            <%= drop_down_divider %>
            <%= menu_item "Profile", user_root_path %>
            <%= drop_down_divider %>
            <% if !current_user.customers.empty? -%>
              <%= drop_down_submenu 'Customers' do %>
                <% for customer in Customer.find(:all) %>
                  <% if current_user.customers.include?(customer) -%>
                    <% if !session[:current_customer].blank? && (session[:current_customer] == customer.id.to_s) -%>
                      <li class="active"><%= link_to customer.name, "#" %></li>
                    <% else -%>
                      <li><%= link_to customer.name, root_path(:current_customer => customer.id) %></li>
                    <% end -%>
                  <% end %>
                <% end %>
              <% end %>
              <%= drop_down_divider %>
            <% end %>
            <%= menu_item "Log Out", destroy_user_session_path, :method => 'delete' %>
          <% end %>
        <% else %>
          <%= menu_item "Log in", new_user_session_path %>
        <% end %>
      <% end %>
    <% end %>   

    <div class="container-fluid">
      <div class="row-fluid">
<!--         <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>--><!--/.well -->
<!--        </div>--><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
    <div class="container-fluid" id="footer">
      <div class="row-fluid">
        <footer>
          <p>&copy; nVisionary, Inc. 2014</p>
        </footer>
      </div>
    </div> <!-- /container -->

  </body>
</html>